"""Code-versioned runtime safety and determinism policy.

These values are invariants of the runtime implementation, not per-run tuning
knobs. They remain written to every run manifest for auditability.
"""

MARKET_DATA_QUEUE_CAPACITY = 4096
WS_POSITION_SILENCE_SECONDS = 15.0
WS_GLOBAL_SILENCE_SECONDS = 15.0
REST_CONTROL_INTERVAL_SECONDS = 60.0
REST_CONTROL_ANOMALY_PERCENT = 0.25
POSITION_FALLBACK_INTERVAL_SECONDS = 10.0
DECISION_WINDOW_GRACE_SECONDS = 5.0

CANDLE_CLOCK_GRACE_SECONDS = 1.0
CANDLE_MAX_CARRY_FORWARD_AGE_SECONDS = 180.0
CANDLE_ORDERING_DROP_DEGRADE_COUNT = 3
CANDLE_ORDERING_DROP_DEGRADE_RATIO = 0.10

POSITION_RECONCILIATION_GRACE_SECONDS = 30.0
POSITION_RECONCILIATION_REQUIRED_MISSES = 3
POSITION_RECONCILIATION_MISS_INTERVAL_SECONDS = 10.0
UNKNOWN_ORDER_LOOKUP_INTERVAL_SECONDS = 15.0
UNKNOWN_ORDER_MAX_AGE_MINUTES = 30.0

ETORO_INSTRUMENT_RESOLUTION_MIN_INTERVAL_SECONDS = 1.05

JOURNAL_WRITE_PARTIAL_SUMMARY = True
JOURNAL_PARTIAL_SUMMARY_INTERVAL_MINUTES = 15
